In [4]:
import pandas as pd
import numpy as np

In [6]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
df= pd.DataFrame(data= np.arange(0,20).reshape(5,4), index= ["Row1", "Row2", "Row3", "Row4", "Row5"], columns=["column1", "column2",
                                                                                                           "column3","column4"])

In [9]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [13]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [17]:
#indexing
#colname,rowindex(loc),row index column index number(iloc)
df[['column1', 'column2', 'column3']]
type(df[['column1', 'column2', 'column3']])

pandas.core.frame.DataFrame

In [18]:
type(df['column1']) #Series

pandas.core.series.Series

In [23]:
df.loc[['Row3', 'Row4']] #Using row index name

column1  column2  column3  column4
Row3        8        9       10       11
Row4       12       13       14       15

In [24]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [26]:
df.iloc[2:4,0:2] #Using iloc

column1  column2
Row3        8        9
Row4       12       13

In [27]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [29]:
df.iloc[0:,0:4:3]

column1  column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

In [30]:
#convert df in arrays
df.iloc[0:,0:4:3].values

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15],
       [16, 19]])

In [31]:
##Basic operation
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [33]:
df= pd.DataFrame(data= [[1, np.nan,2], [3, 4,2]], index= ["Row1", "Row2"], columns=["column1", "column2","column3"])

In [34]:
df.head()

column1  column2  column3
Row1        1      NaN        2
Row2        3      4.0        2

In [36]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [39]:
df.isnull().sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [42]:
df['column3'].value_counts()

column3
2    2
Name: count, dtype: int64

In [44]:
df['column2'].unique()

array([nan,  4.])

In [46]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [47]:
df>2

column1  column2  column3  column4
Row1    False    False    False     True
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row5     True     True     True     True